### ISSUE TITLE
Web App

### ISSUE THREAD

**Issue by thisisadiyoga** [zululim/CS2102_2021_S1_Team55#1]
What's the link to web app?

**Comment by zululim** [comment]
Good afternoon prof,

Apologies for leaving out the link, I have added in under the folder titled ‘web app link’

Regards,
Ryan Lim

**Comment by thisisadiyoga** [comment]
Is the link supposed to be: http://cs2102-2021-s1-team55.herokuapp.com/?
It gives application error currently.

**Comment by zululim** [comment]
Good afternoon Prof,

Unfortunately none of the members of the group are familiar with Heroku and we were not able to debug the issue in time despite following heroku’s instructions. We created the demo video locally and the website is able to work when hosted locally

Regards,
Ryan Lim

**Comment by thisisadiyoga** [comment]
Ah, ok.  I'll close this issue then.
